services:
  web:
    image: nginx:latest
    container_name: web-prod
    volumes:
     - /etc/nginx:/etc/nginx
     - /usr/share/nginx/html:/usr/share/nginx/html
     - /etc/letsencrypt:/etc/letsencrypt
     - /home/nginx:/home/nginx
     - /usr/src/app:/usr/src/app
     - /mnt/volume-2/gitlab/nginx:/var/nginx
    environment:
     - NGINX_HOST=mmaluta.ddnss.de
     - NGINX_PORT=80
    ports:
     - 443:443
     - 80:80
    restart: unless-stopped
    networks:
      - homeserver
      - web


networks:
  homeserver:
    name: homeserver
    external: true

  web:
    name: web
    external: true
